export default {
    aboutSite: 'About this site',
    link1Text: 'Site Link 1',
    link2Text: 'Site Link 2',
    getHelpText: 'Get help',
    phoneText: '888-888-8888',
    emailText: 'Support@email.com',
    faxText: 'Fax: 777-777-7777',
    stayInTouchText: 'Stay in touch',
    copyright2019Text: 'Copyright 2019',
    linkAllumaText: 'Alluma',
    linkPolicyText: 'Privacy Policy',
    linkNonDiscriminationPolicyText: 'Non-discrimination Policy',
    linkTermsText: 'Terms of Use',
    facebookLink: 'https://www.facebook.com/WeAreAlluma/?ref=page_internal',
    twitterLink: 'https://twitter.com/WeAreAlluma',
    allumaPageLink: 'https://www.alluma.org/',
    linkedInLink: 'https://www.alluma.org/',
    emailUrl: 'mailto:support@email.com',
}